### ISSUE TITLE
Implement King Movement and Validation Logic

### ISSUE THREAD

**Issue by CodeMaverick2** [CodeMaverick2/Chess_group-16#1]
---

### **King Movement:**
- The king can move one square in any direction: horizontally, vertically, or diagonally.
- The king cannot move to a square that is under attack by an opponent’s piece.

### **Move Validation:**
1. **Valid Moves:**
   - Ensure the king's move adheres to the movement rules (one square in any direction).
   - If the destination square is occupied by a friendly piece, the move should be rejected.
   - Check that the destination square is not occupied by a friendly piece.
   
2. **Check for Check:**
   - Ensure the king does not move to a square where it would be in check (i.e., a position where it could be captured on the next turn).
   - If the move places the king in check (i.e., a position where it could be captured on the next turn), the move should also be rejected.
---

**Comment by GSRK-BZA** [comment]
Assign this to me

**Comment by GSRK-BZA** [comment]
Yo I made a pr accept it
